Forum\Bundle\HomeBundle\Entity\Question:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        content:
            type: string
            length: 255
        createTime:
            type: datetime
            column: create_time
        uId:
            type: integer
            column: u_id
    lifecycleCallbacks: {  }
