Forum\Bundle\HomeBundle\Entity\User:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        email:
            type: string
            length: 255
        phone:
            type: string
            length: 255
        password:
            type: string
            length: 255
        permission:
            type: integer
        createTime:
            type: datetime
            column: create_time
        updateTime:
            type: datetime
            column: update_time
    lifecycleCallbacks: {  }
