Forum\Bundle\HomeBundle\Entity\UserQuestionMapping:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        uId:
            type: integer
            column: u_id
        qId:
            type: integer
            column: q_id
    lifecycleCallbacks: {  }
